FROM python:3
ADD holamundo.py /
CMD ["python", "./holamundo.py"] 

#solo puede haber un cmd por dockerfile, pueden haber varios add
#los comentarios solo pueden empezar en una linea, no estar a la mitad